// Code generated by sqlc. DO NOT EDIT.
// source: account_receiveables.sql

package db

import (
	"context"
	"database/sql"
)

const createAccountReceiveable = `-- name: CreateAccountReceiveable :one
INSERT INTO account_receiveables (
    owner_id, 
    code, 
    "name", 
    description, 
    src_account_id, 
    dst_account_id, 
    recurring_type, 
    recurring_periode, 
    created_by,
    updated_by
) 
VALUES(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, owner_id, code, name, description, src_account_id, dst_account_id, recurring_type, recurring_periode, user_type, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateAccountReceiveableParams struct {
	OwnerID          int32          `json:"owner_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	SrcAccountID     int32          `json:"src_account_id"`
	DstAccountID     int32          `json:"dst_account_id"`
	RecurringType    int16          `json:"recurring_type"`
	RecurringPeriode int16          `json:"recurring_periode"`
	CreatedBy        int32          `json:"created_by"`
	UpdatedBy        int32          `json:"updated_by"`
}

func (q *Queries) CreateAccountReceiveable(ctx context.Context, arg CreateAccountReceiveableParams) (AccountReceiveable, error) {
	row := q.db.QueryRowContext(ctx, createAccountReceiveable,
		arg.OwnerID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.SrcAccountID,
		arg.DstAccountID,
		arg.RecurringType,
		arg.RecurringPeriode,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AccountReceiveable
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SrcAccountID,
		&i.DstAccountID,
		&i.RecurringType,
		&i.RecurringPeriode,
		&i.UserType,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteAccountReceiveable = `-- name: DeleteAccountReceiveable :exec
DELETE FROM account_receiveables
WHERE id = $1
`

func (q *Queries) DeleteAccountReceiveable(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAccountReceiveable, id)
	return err
}

const getAccountReceiveable = `-- name: GetAccountReceiveable :one
SELECT id, owner_id, code, name, description, src_account_id, dst_account_id, recurring_type, recurring_periode, user_type, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM account_receiveables
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountReceiveable(ctx context.Context, id int32) (AccountReceiveable, error) {
	row := q.db.QueryRowContext(ctx, getAccountReceiveable, id)
	var i AccountReceiveable
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SrcAccountID,
		&i.DstAccountID,
		&i.RecurringType,
		&i.RecurringPeriode,
		&i.UserType,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getAccountReceiveableForUpdate = `-- name: GetAccountReceiveableForUpdate :one
SELECT id, owner_id, code, name, description, src_account_id, dst_account_id, recurring_type, recurring_periode, user_type, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM account_receiveables
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAccountReceiveableForUpdate(ctx context.Context, id int32) (AccountReceiveable, error) {
	row := q.db.QueryRowContext(ctx, getAccountReceiveableForUpdate, id)
	var i AccountReceiveable
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SrcAccountID,
		&i.DstAccountID,
		&i.RecurringType,
		&i.RecurringPeriode,
		&i.UserType,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAccountReceiveables = `-- name: ListAccountReceiveables :many
SELECT id, owner_id, code, name, description, src_account_id, dst_account_id, recurring_type, recurring_periode, user_type, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM account_receiveables
WHERE owner_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListAccountReceiveablesParams struct {
	OwnerID int32 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListAccountReceiveables(ctx context.Context, arg ListAccountReceiveablesParams) ([]AccountReceiveable, error) {
	rows, err := q.db.QueryContext(ctx, listAccountReceiveables, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountReceiveable
	for rows.Next() {
		var i AccountReceiveable
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.SrcAccountID,
			&i.DstAccountID,
			&i.RecurringType,
			&i.RecurringPeriode,
			&i.UserType,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountReceiveable = `-- name: UpdateAccountReceiveable :one
UPDATE account_receiveables
SET owner_id=$2, 
    code=$3, 
    "name"=$4, 
    description=$5, 
    src_account_id=$6, 
    dst_account_id=$7, 
    recurring_type=$8, 
    recurring_periode=$9, 
    updated_at=now(),
    updated_by=$10
WHERE id = $1
RETURNING id, owner_id, code, name, description, src_account_id, dst_account_id, recurring_type, recurring_periode, user_type, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateAccountReceiveableParams struct {
	ID               int32          `json:"id"`
	OwnerID          int32          `json:"owner_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	SrcAccountID     int32          `json:"src_account_id"`
	DstAccountID     int32          `json:"dst_account_id"`
	RecurringType    int16          `json:"recurring_type"`
	RecurringPeriode int16          `json:"recurring_periode"`
	UpdatedBy        int32          `json:"updated_by"`
}

func (q *Queries) UpdateAccountReceiveable(ctx context.Context, arg UpdateAccountReceiveableParams) (AccountReceiveable, error) {
	row := q.db.QueryRowContext(ctx, updateAccountReceiveable,
		arg.ID,
		arg.OwnerID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.SrcAccountID,
		arg.DstAccountID,
		arg.RecurringType,
		arg.RecurringPeriode,
		arg.UpdatedBy,
	)
	var i AccountReceiveable
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.SrcAccountID,
		&i.DstAccountID,
		&i.RecurringType,
		&i.RecurringPeriode,
		&i.UserType,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
