// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/tabbed/pqtype"
)

type AccountPayable struct {
	ID               int32          `json:"id"`
	OwnerID          int32          `json:"owner_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	SrcAccountID     int32          `json:"src_account_id"`
	DstAccountID     int32          `json:"dst_account_id"`
	RecurringType    int16          `json:"recurring_type"`
	RecurringPeriode int16          `json:"recurring_periode"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        int32          `json:"created_by"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        int32          `json:"updated_by"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	DeletedBy        sql.NullInt32  `json:"deleted_by"`
}

type AccountPayableRule struct {
	ID        int32           `json:"id"`
	OwnerID   int32           `json:"owner_id"`
	ApID      int32           `json:"ap_id"`
	PeriodID  int32           `json:"period_id"`
	Rule      json.RawMessage `json:"rule"`
	CreatedAt time.Time       `json:"created_at"`
	CreatedBy int32           `json:"created_by"`
	UpdatedAt time.Time       `json:"updated_at"`
	UpdatedBy int32           `json:"updated_by"`
	DeletedAt sql.NullTime    `json:"deleted_at"`
	DeletedBy sql.NullInt32   `json:"deleted_by"`
}

type AccountReceiveable struct {
	ID               int32          `json:"id"`
	OwnerID          int32          `json:"owner_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	SrcAccountID     int32          `json:"src_account_id"`
	DstAccountID     int32          `json:"dst_account_id"`
	RecurringType    int16          `json:"recurring_type"`
	RecurringPeriode int16          `json:"recurring_periode"`
	UserType         int16          `json:"user_type"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        int32          `json:"created_by"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        int32          `json:"updated_by"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	DeletedBy        sql.NullInt32  `json:"deleted_by"`
}

type AccountReceiveableRule struct {
	ID        int32           `json:"id"`
	OwnerID   int32           `json:"owner_id"`
	ArID      int32           `json:"ar_id"`
	PeriodID  int32           `json:"period_id"`
	Rule      json.RawMessage `json:"rule"`
	CreatedAt time.Time       `json:"created_at"`
	CreatedBy int32           `json:"created_by"`
	UpdatedAt time.Time       `json:"updated_at"`
	UpdatedBy int32           `json:"updated_by"`
	DeletedAt sql.NullTime    `json:"deleted_at"`
	DeletedBy sql.NullInt32   `json:"deleted_by"`
}

type GeneralLedger struct {
	ID        int32         `json:"id"`
	OwnerID   int32         `json:"owner_id"`
	Number    string        `json:"number"`
	Status    int16         `json:"status"`
	Date      time.Time     `json:"date"`
	CreatedAt time.Time     `json:"created_at"`
	CreatedBy int32         `json:"created_by"`
	UpdatedAt time.Time     `json:"updated_at"`
	UpdatedBy int32         `json:"updated_by"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	DeletedBy sql.NullInt32 `json:"deleted_by"`
}

type GeneralLedgerDetail struct {
	ID              int32         `json:"id"`
	OwnerID         int32         `json:"owner_id"`
	GeneralLedgerID int32         `json:"general_ledger_id"`
	AccountID       int32         `json:"account_id"`
	Debit           string        `json:"debit"`
	Credit          string        `json:"credit"`
	BalanceBefore   string        `json:"balance_before"`
	Balance         string        `json:"balance"`
	CreatedAt       time.Time     `json:"created_at"`
	CreatedBy       int32         `json:"created_by"`
	UpdatedAt       time.Time     `json:"updated_at"`
	UpdatedBy       int32         `json:"updated_by"`
	DeletedAt       sql.NullTime  `json:"deleted_at"`
	DeletedBy       sql.NullInt32 `json:"deleted_by"`
}

type Invoice struct {
	ID                    int32                 `json:"id"`
	OwnerID               int32                 `json:"owner_id"`
	UserID                int32                 `json:"user_id"`
	Number                string                `json:"number"`
	ArID                  int32                 `json:"ar_id"`
	Status                int16                 `json:"status"`
	Amount                string                `json:"amount"`
	AmountPaid            string                `json:"amount_paid"`
	Date                  time.Time             `json:"date"`
	DueDate               time.Time             `json:"due_date"`
	AdditionalInfo        pqtype.NullRawMessage `json:"additional_info"`
	PaymentID             sql.NullInt32         `json:"payment_id"`
	DiscountID            sql.NullInt32         `json:"discount_id"`
	CreatedAt             time.Time             `json:"created_at"`
	CreatedBy             int32                 `json:"created_by"`
	UpdatedAt             time.Time             `json:"updated_at"`
	UpdatedBy             int32                 `json:"updated_by"`
	DeletedAt             sql.NullTime          `json:"deleted_at"`
	DeletedBy             sql.NullInt32         `json:"deleted_by"`
	PeriodID              sql.NullInt32         `json:"period_id"`
	ClassProgramID        sql.NullInt32         `json:"class_program_id"`
	ClassLevelID          sql.NullInt32         `json:"class_level_id"`
	ClassSpecializationID sql.NullInt32         `json:"class_specialization_id"`
	Male                  sql.NullBool          `json:"male"`
	RecurringType         int16                 `json:"recurring_type"`
	RecurringPeriod       int16                 `json:"recurring_period"`
	Installment           int16                 `json:"installment"`
	Mutation              sql.NullBool          `json:"mutation"`
	Boarding              sql.NullBool          `json:"boarding"`
	AdmissionLineID       int16                 `json:"admission_line_id"`
	AdmissionBatchID      int16                 `json:"admission_batch_id"`
}

type Journal struct {
	ID              int32          `json:"id"`
	OwnerID         int32          `json:"owner_id"`
	Number          string         `json:"number"`
	Date            time.Time      `json:"date"`
	GeneralLedgerID sql.NullInt32  `json:"general_ledger_id"`
	Status          int16          `json:"status"`
	Amount          string         `json:"amount"`
	Description     sql.NullString `json:"description"`
	ReffModel       sql.NullString `json:"reff_model"`
	ReffModelID     sql.NullInt32  `json:"reff_model_id"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       int32          `json:"created_by"`
	UpdatedAt       time.Time      `json:"updated_at"`
	UpdatedBy       int32          `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullInt32  `json:"deleted_by"`
}

type JournalDetail struct {
	ID          int32          `json:"id"`
	OwnerID     int32          `json:"owner_id"`
	AccountID   int64          `json:"account_id"`
	JournalID   int32          `json:"journal_id"`
	Amount      string         `json:"amount"`
	ReffModel   sql.NullString `json:"reff_model"`
	ReffModelID sql.NullInt32  `json:"reff_model_id"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int32          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int32          `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullInt32  `json:"deleted_by"`
}

type MBank struct {
	ID        int32          `json:"id"`
	OwnerID   int32          `json:"owner_id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	Alias     sql.NullString `json:"alias"`
	CreatedAt time.Time      `json:"created_at"`
	CreatedBy int32          `json:"created_by"`
	UpdatedAt time.Time      `json:"updated_at"`
	UpdatedBy int32          `json:"updated_by"`
}

type MBankAccount struct {
	ID         int32     `json:"id"`
	OwnerID    int32     `json:"owner_id"`
	BankID     int32     `json:"bank_id"`
	BranchName string    `json:"branch_name"`
	Name       string    `json:"name"`
	Number     string    `json:"number"`
	CreatedAt  time.Time `json:"created_at"`
	CreatedBy  int32     `json:"created_by"`
	UpdatedAt  time.Time `json:"updated_at"`
	UpdatedBy  int32     `json:"updated_by"`
}

type MBookPeriod struct {
	ID          int32          `json:"id"`
	OwnerID     int32          `json:"owner_id"`
	Code        sql.NullString `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int16          `json:"status"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int32          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int32          `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullInt32  `json:"deleted_by"`
}

type MChartOfAccount struct {
	ID          int32          `json:"id"`
	OwnerID     int32          `json:"owner_id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    int16          `json:"category"`
	Level       int16          `json:"level"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int32          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int32          `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullInt32  `json:"deleted_by"`
}

type MDiscount struct {
	ID          int32          `json:"id"`
	OwnerID     int32          `json:"owner_id"`
	Code        sql.NullString `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
	Value       string         `json:"value"`
	IsPercent   bool           `json:"is_percent"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   int32          `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UpdatedBy   int32          `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullInt32  `json:"deleted_by"`
}

type MVirtualAccount struct {
	ID        int32     `json:"id"`
	OwnerID   int32     `json:"owner_id"`
	BankID    int32     `json:"bank_id"`
	Number    string    `json:"number"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy int32     `json:"created_by"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy int32     `json:"updated_by"`
}

type Purchase struct {
	ID             int32                 `json:"id"`
	OwnerID        int32                 `json:"owner_id"`
	UserID         int32                 `json:"user_id"`
	Number         string                `json:"number"`
	ApID           int32                 `json:"ap_id"`
	Status         int16                 `json:"status"`
	Amount         string                `json:"amount"`
	AmountPaid     string                `json:"amount_paid"`
	Date           time.Time             `json:"date"`
	DueDate        time.Time             `json:"due_date"`
	AdditionalInfo pqtype.NullRawMessage `json:"additional_info"`
	PeriodID       sql.NullInt32         `json:"period_id"`
	ExpenseID      sql.NullInt32         `json:"expense_id"`
	DiscountID     sql.NullInt32         `json:"discount_id"`
	CreatedAt      time.Time             `json:"created_at"`
	CreatedBy      int32                 `json:"created_by"`
	UpdatedAt      time.Time             `json:"updated_at"`
	UpdatedBy      int32                 `json:"updated_by"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	DeletedBy      sql.NullInt32         `json:"deleted_by"`
}

type TrxBankTransfer struct {
	ID             int32                 `json:"id"`
	OwnerID        int32                 `json:"owner_id"`
	UserID         int32                 `json:"user_id"`
	BankID         int32                 `json:"bank_id"`
	Number         sql.NullString        `json:"number"`
	Date           time.Time             `json:"date"`
	Status         int16                 `json:"status"`
	Amount         string                `json:"amount"`
	Description    sql.NullString        `json:"description"`
	DestModel      sql.NullString        `json:"dest_model"`
	DestModelID    sql.NullInt32         `json:"dest_model_id"`
	AccountOwner   sql.NullString        `json:"account_owner"`
	AccountNumber  sql.NullString        `json:"account_number"`
	AdditionalInfo pqtype.NullRawMessage `json:"additional_info"`
	TrxReceivesID  int32                 `json:"trx_receives_id"`
	CreatedAt      time.Time             `json:"created_at"`
	CreatedBy      int32                 `json:"created_by"`
	UpdatedAt      time.Time             `json:"updated_at"`
	UpdatedBy      int32                 `json:"updated_by"`
}

type TrxExpense struct {
	ID            int32          `json:"id"`
	OwnerID       int32          `json:"owner_id"`
	UserID        int32          `json:"user_id"`
	Number        sql.NullString `json:"number"`
	Amount        string         `json:"amount"`
	Date          time.Time      `json:"date"`
	Status        int16          `json:"status"`
	Description   sql.NullString `json:"description"`
	PaymentMethod int16          `json:"payment_method"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     int32          `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     int32          `json:"updated_by"`
	JournalID     sql.NullInt32  `json:"journal_id"`
}

type TrxExpenseDetail struct {
	ID            int32          `json:"id"`
	TrxExpensesID int32          `json:"trx_expenses_id"`
	Amount        string         `json:"amount"`
	IsSource      bool           `json:"is_source"`
	AccountID     int32          `json:"account_id"`
	Model         sql.NullString `json:"model"`
	ModelID       sql.NullInt32  `json:"model_id"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     int32          `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     int32          `json:"updated_by"`
}

type TrxReceife struct {
	ID            int32          `json:"id"`
	OwnerID       int32          `json:"owner_id"`
	UserID        int32          `json:"user_id"`
	Number        sql.NullString `json:"number"`
	Amount        string         `json:"amount"`
	Date          time.Time      `json:"date"`
	Status        int16          `json:"status"`
	Description   sql.NullString `json:"description"`
	PaymentMethod int16          `json:"payment_method"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     int32          `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     int32          `json:"updated_by"`
	JournalID     sql.NullInt32  `json:"journal_id"`
}

type TrxReceiveDetail struct {
	ID            int32          `json:"id"`
	TrxReceivesID int32          `json:"trx_receives_id"`
	Amount        string         `json:"amount"`
	IsSource      bool           `json:"is_source"`
	AccountID     int32          `json:"account_id"`
	Model         sql.NullString `json:"model"`
	ModelID       sql.NullInt32  `json:"model_id"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     int32          `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     int32          `json:"updated_by"`
}

type TrxWallet struct {
	ID            int32          `json:"id"`
	WalletID      int32          `json:"wallet_id"`
	Amount        string         `json:"amount"`
	BalanceBefore string         `json:"balance_before"`
	Balance       string         `json:"balance"`
	DestModel     sql.NullString `json:"dest_model"`
	DestModelID   sql.NullInt32  `json:"dest_model_id"`
	TrxReceivesID int32          `json:"trx_receives_id"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     int64          `json:"created_by"`
	UpdatedAt     time.Time      `json:"updated_at"`
	UpdatedBy     int32          `json:"updated_by"`
	Debit         bool           `json:"debit"`
}

type Wallet struct {
	ID         int32                 `json:"id"`
	OwnerID    int32                 `json:"owner_id"`
	UserID     int32                 `json:"user_id"`
	Code       string                `json:"code"`
	Name       string                `json:"name"`
	Alias      sql.NullString        `json:"alias"`
	Balance    string                `json:"balance"`
	AccountID  sql.NullInt32         `json:"account_id"`
	OtherInfo  pqtype.NullRawMessage `json:"other_info"`
	AllowMinus sql.NullBool          `json:"allow_minus"`
	CreatedAt  time.Time             `json:"created_at"`
	CreatedBy  int32                 `json:"created_by"`
	UpdatedAt  time.Time             `json:"updated_at"`
	UpdatedBy  int32                 `json:"updated_by"`
	DeletedAt  sql.NullTime          `json:"deleted_at"`
	DeletedBy  sql.NullInt32         `json:"deleted_by"`
}
